targets:
  $default:
    builders:
      copy_with_extension_gen|copy_with_extension_gen:
        enabled: true
        generate_for:
          - "**/models/**.dart"
      json_serializable|json_serializable:
        options:
          field_rename: pascal
        enabled: true
        generate_for:
          - "**/models/**.dart"
      hive_generator|hive_generator:
        enabled: true
        generate_for:
          - "**/models/**.dart"